# profiles.yml

ADO_Assignment_final:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: qd77687.ap-southeast-1
      user: groupaccount1
      password: Groupaccount1
      database: ASSIGNMENT2
      warehouse: NWT_WAREHOUSE
      schema: NWT
      role: ACCOUNTADMIN