ALTER TABLE ASSIGNMENT2.NWT.RAW_ORDER
ADD SHIPPEDDATE_FIXED DATE DEFAULT '1970-01-01 00:00:00';

UPDATE ASSIGNMENT2.NWT.RAW_ORDER
SET SHIPPEDDATE_FIXED = SHIPPEDDATE
WHERE SHIPPEDDATE IS NULL;

ALTER TABLE ASSIGNMENT2.NWT.RAW_ORDER
DROP COLUMN SHIPPEDDATE;
