USE SCHEMA FRESH_COLUMNS;
ALTER TABLE FRESH_PRODUCT ADD COLUMN ListPrice INT; 
ALTER TABLE FRESH_PRODUCT ADD COLUMN UnitCost INT;
ALTER TABLE FRESH_PRODUCT ADD COLUMN Discontinued VARCHAR;
ALTER TABLE FRESH_PRODUCT ADD COLUMN CategoryName VARCHAR;
ALTER TABLE FRESH_PRODUCT ADD COLUMN companyName VARCHAR;