SELECT 
    ORDERID,
    PRODUCTID,
    COSTPRICE,
    UNITPRICE,
    QUANTITY,
    PRODUCTPRICE,
    PRODUCTCOST,
    DISCOUNT
FROM {{ ref('stg_jovin') }}
GROUP BY
    ORDERID,
    PRODUCTID,
    UNITPRICE,
    COSTPRICE,
    QUANTITY,
    PRODUCTPRICE, 
    PRODUCTCOST,
    DISCOUNT