/*SELECT 
  EMPLOYEEID,
  FIRSTNAME, 
  ORDERDATE,
  SUM(OrderPrice) AS TotalOrderPrice
FROM {{ ref('stg_markell') }}
WHERE ORDERDATE >= '04-Jul-1996	' AND ORDERDATE < '06-May-1998'
GROUP BY EMPLOYEEID, FIRSTNAME, ORDERDATE*/
