SELECT 
    EMPLOYEEID,
    FIRSTNAME,
    CUSTOMERID,
    COUNT(DISTINCT ORDERID) AS CustomerOrderCount
FROM {{ ref('stg_markell') }}
GROUP BY 
    EMPLOYEEID,
    FIRSTNAME,
    CUSTOMERID
HAVING 
    COUNT(DISTINCT ORDERID) > 1
