SELECT 
    ORDERID, 
    PRODUCTID,
    SUM(QUANTITY) AS QUANTITY,
    SUM(PRODUCTPRICE) AS TOTAL_PRICE,
    PRODUCTCOST,
    SHIPCOUNTRY,
    SHIPCITY,
    CATEGORYNAME
FROM {{ ref('stg_jovin') }}
GROUP BY 
    ORDERID,
    PRODUCTID,
    QUANTITY,
    PRODUCTCOST,
    SHIPCITY,
    SHIPCOUNTRY,
    CATEGORYNAME,
    PRODUCTPRICE