SELECT 
    ORDERID,
    PRODUCTID, 
    SUM(QUANTITY) AS QUANTITYSOLD,
    CUSTOMERID,
    EMPLOYEEID, 
    CATEGORYNAME,
    PRODUCTNAME
FROM {{ ref('stg_jovin') }}
GROUP BY 
    ORDERID, 
    PRODUCTID, 
    CUSTOMERID,
    EMPLOYEEID, 
    CATEGORYNAME,
    PRODUCTNAME